/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fobos_sdr.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d1c14b2acde7f49d2abdf8ad318712e3)                     */
/***********************************************************************************/
 
#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/RigExpert/fobos_sdr.h>
// pydoc.h is automatically generated in the build directory
#include <fobos_sdr_pydoc.h>

void bind_fobos_sdr(py::module& m)
{

    using fobos_sdr    = gr::RigExpert::fobos_sdr;


    py::class_<fobos_sdr, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fobos_sdr>>(m, "fobos_sdr", D(fobos_sdr))

        .def(py::init(&fobos_sdr::make),
           D(fobos_sdr,make)
        )
        



        ;




}








