/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fobos_sdr.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f06b7121ccf4e00c9fa9af4432643237)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/RigExpert/fobos_sdr.h>
// pydoc.h is automatically generated in the build directory
#include <fobos_sdr_pydoc.h>

void bind_fobos_sdr(py::module& m)
{

    using fobos_sdr    = ::gr::RigExpert::fobos_sdr;


    py::class_<fobos_sdr, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fobos_sdr>>(m, "fobos_sdr", D(fobos_sdr))

        .def(py::init(&fobos_sdr::make),
           py::arg("index") = 0,
           py::arg("frequency") = 100.0,
           py::arg("samplerate") = 10.0,
           py::arg("lna_gain") = 0,
           py::arg("vga_gain") = 0,
           py::arg("direct_sampling") = 0,
           py::arg("clock_source") = 0,
           D(fobos_sdr,make)
        )
        
        .def("set_frequency",&fobos_sdr::set_frequency,       
            py::arg("frequency"),
            D(fobos_sdr,set_frequency)
        )
       
        .def("set_samplerate",&fobos_sdr::set_samplerate,       
            py::arg("samplerate"),
            D(fobos_sdr,set_samplerate)
        )

        .def("set_lna_gain",&fobos_sdr::set_lna_gain,       
            py::arg("lna_gain"),
            D(fobos_sdr,set_lna_gain)
        )

        .def("set_vga_gain",&fobos_sdr::set_vga_gain,       
            py::arg("vga_gain"),
            D(fobos_sdr,set_vga_gain)
        )
        .def("set_direct_sampling",&fobos_sdr::set_direct_sampling,       
            py::arg("direct_sampling"),
            D(fobos_sdr,set_direct_sampling)
        )

        .def("set_clock_source",&fobos_sdr::set_clock_source,       
            py::arg("clock_source"),
            D(fobos_sdr,set_clock_source)
        )        
        ;




}








